name: RHI main CI
          
on:
  push:
    branches: [ main, master, 26-enable-cicd ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        build_type: [Release]
        cpp_standard: [20]
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: macos-latest
            compiler: clang++
          - os: windows-latest
            compiler: msvc
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: Install C++ tools
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        cmake: true
        ninja: true
        conan: true
        ccache: true
        clang-format: true
        clang-tidy: true

    - name: Conan Profile detect
      run: |
            conan --version
            conan profile detect

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
         # You can set the Vulkan SDK version to download.
         # Defaults to latest version, if version not set.
         vulkan_version: 1.4.309.0
         optional_components: com.lunarg.vulkan.vma
         install_runtime: true
         cache: true
         stripdown: true
         # You can install a software rasterizer.
         #install_swiftshader: true
         install_lavapipe: true
    
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo ./install_linux.sh
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake ccache
        # Add other dependencies if needed
    
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Install dependencies (windows)"
        
    - name: Configure CMake
      run: | 
          cmake -B CMakeCache -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build project
      run: cmake --build CMakeCache --config ${{ matrix.build_type }}

    - name: Install project
      run: cmake --install CMakeCache --prefix "Build/${{ matrix.build_type }}" --config ${{ matrix.build_type }}
    
    - name: Run tests
      run: |
        cd ${{github.workspace}}/CMakeCache
        ctest --output-on-failure -C ${{ matrix.build_type }}