name: RHI main CI
          
on:
  push:
    branches: [ main, master, 26-enable-cicd ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        build_type: [Release]
        cpp_standard: [20]
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: macos-latest
            compiler: clang++
          - os: windows-latest
            compiler: msvc
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: Install C++ tools
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        cmake: true
        ninja: true
        conan: true
        ccache: true
        clang-format: true
        clang-tidy: true

    - name: Conan Profile detect
      run: |
            conan --version
            conan profile detect

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
         # You can set the Vulkan SDK version to download.
         # Defaults to latest version, if version not set.
         vulkan_version: 1.4.309.0
         optional_components: com.lunarg.vulkan.vma
         install_runtime: true
         cache: true
         stripdown: true
         # You can install a software rasterizer.
         #install_swiftshader: true
         install_lavapipe: true
    
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        # install system packages
        sudo apt-get install libgl-dev libgl1-mesa-dev \
        libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev \
        libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxtst-dev \
        libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev \
        libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev \
        uuid-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev libxcb-util-dev libxcb-util0-dev
        #install vulkan libraries
        sudo apt-get install libvulkan-dev glslc
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake ccache
        # Add other dependencies if needed
    
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Install dependencies (windows)"
        
    - name: Configure CMake
      run: | 
          cmake -B CMakeCache -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build project
      run: cmake --build CMakeCache --config ${{ matrix.build_type }}

    - name: Install project
      run: cmake --install CMakeCache --prefix "Build/${{ matrix.build_type }}" --config ${{ matrix.build_type }}
    
    - name: Run tests
      run: |
        cd ${{github.workspace}}/CMakeCache
        ctest --output-on-failure -C ${{ matrix.build_type }}